CREATE TABLE IF NOT EXISTS user_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_product_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_products_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_user_products_company_product FOREIGN KEY (company_product_id)
        REFERENCES company_products(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_user_products_role FOREIGN KEY (role_id)
        REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT uq_user_company_product UNIQUE (user_id, company_product_id)
);
CREATE INDEX IF NOT EXISTS idx_user_products_user ON user_products(user_id);
CREATE INDEX IF NOT EXISTS idx_user_products_company_product ON user_products(company_product_id);
CREATE INDEX IF NOT EXISTS idx_user_products_role ON user_products(role_id);
CREATE INDEX IF NOT EXISTS idx_user_products_status ON user_products(status);
