import fs from "node:fs/promises";
import path from "node:path";

import { db } from "../config/database.js";

const migrationsDirectory = path.join(__dirname, "migrations");

async function migrate() {
  const pool = db;

  const client = await pool.connect();

  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS migrations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        migration VARCHAR(255) NOT NULL,
        executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_migrations_migration UNIQUE (migration)
      );
    `);

    const { rows } = await client.query<{ migration: string }>(
      `SELECT migration FROM migrations`,
    );

    const executedMigrations = new Set(rows.map((row) => row.migration));
    const files = await fs.readdir(migrationsDirectory);
    const migrations = files.filter((file) => file.endsWith(".sql")).sort();

    for (const migration of migrations) {
      if (executedMigrations.has(migration)) continue;

      console.log(`Running migration: ${migration}`);
      const filePath = path.join(migrationsDirectory, migration);
      const sql = await fs.readFile(filePath, "utf8");

      await client.query("BEGIN");

      try {
        // PostgreSQL can execute a migration file as a multi-statement
        // simple query, so PL/pgSQL function bodies and DO blocks remain intact.
        await client.query(sql);

        await client.query(
          `INSERT INTO migrations (migration) VALUES ($1)`,
          [migration],
        );

        await client.query("COMMIT");
        console.log(`Completed migration: ${migration}`);
      } catch (error) {
        await client.query("ROLLBACK");
        console.error(`Migration failed: ${migration}`);
        throw error;
      }
    }

    console.log("All migrations completed.");
  } finally {
    client.release();
    await pool.end();
  }
}

migrate().catch((error) => {
  console.error(error);
  process.exit(1);
});
